### ISSUE TITLE
[Bug]:在Vercel上部署后出现如下错误，请问这是怎么回事儿？

### ISSUE THREAD

**Issue by Liwu253874** [Ykaiqx/Easy-Reverse-Proxy#2]
### 在提交前请确保以下这些

- [X] 在Issues找不到它

### 描述

500: INTERNAL_SERVER_ERROR
Code: FUNCTION_INVOCATION_FAILED
ID: hnd1::jpz5z-1729598105932-d64861e1b1d1

页面截图如下：
![image](https://github.com/user-attachments/assets/11ac4f24-d3da-492b-b83a-1e225bf25251)

**Comment by ykaiqx** [comment]
这个是代码运行出错了。方便提供config.ts的内容吗？

**Comment by Liwu253874** [comment]
config.ts 的内容如下：

import {Proxy} from './util/model';

export let PORT = 370; // 端口

export let PROXY_CODE_SECRET = 'Easy-Reverse-Proxy' // 代理码密钥
// 代理
export let PROXYS: Proxy[] = [ 
  {
        domain: "google.00fa.me",
        url: "https://www.google.com/",
        enable: true,
        template: Google
    }];

**Comment by ykaiqx** [comment]
把template: Google去掉。template是为了对代理的请求以及响应进行更细致的处理（前提是你写了这个模板并且在config.ts引用了）。
修改后的config.ts应是这样
```TypeScript
import {Proxy} from './util/model';

export let PORT = 370; // 端口

export let PROXY_CODE_SECRET = 'Easy-Reverse-Proxy' // 代理码密钥
// 代理
export let PROXYS: Proxy[] = [ 
  {
        domain: "google.00fa.me",
        url: "https://www.google.com/",
        enable: true
    }
];
```

**Comment by Liwu253874** [comment]
非常感谢你的帮助和讲解。
我学习到了。
问题已经解决了
